//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Public_Utilities.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipts
    {
        public int Receipt_ID { get; set; }
        public int Сonsumers_ID { get; set; }
        public int Contract_ID { get; set; }
        public string Status { get; set; }
        public string PaymentAmount { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Contracts Contracts { get; set; }
        public virtual Сonsumers Сonsumers { get; set; }
    }
}
