//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Public_Utilities.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workman
    {
        public int Workman_ID { get; set; }
        public string FullName { get; set; }
        public int User_ID { get; set; }
        public long Phone { get; set; }
        public string Email { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
