//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Public_Utilities.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сonsumers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сonsumers()
        {
            this.Contracts = new HashSet<Contracts>();
            this.Receipts = new HashSet<Receipts>();
        }
    
        public int Сonsumers_ID { get; set; }
        public string FullName { get; set; }
        public long Phone { get; set; }
        public string Email { get; set; }
        public int User_ID { get; set; }
        public string Address { get; set; }
        public System.DateTime Date_Of_Birth { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contracts> Contracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipts> Receipts { get; set; }
        public virtual Users Users { get; set; }
    }
}
